AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "Gemfile"
    - "Rakefile"
    - "bin/*"
    - "paymaya.gemspec"

Lint/BlockAlignment:
  AlignWith: start_of_block

Lint/EndAlignment:
  AlignWith: variable

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/ParameterLists:
  CountKeywordArgs: false

Rails:
  Enabled: true

Rails/RequestReferer:
  EnforcedStyle: referrer

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AutoResourceCleanup:
  Enabled: true

# Style/ConditionalAssignment:
  # EnforcedStyle: assign_inside_condition

Style/Documentation:
  Enabled: false

Style/ExtraSpacing:
  AllowForAlignment: false

Style/FirstArrayElementLineBreak:
  Enabled: false

Style/FirstHashElementLineBreak:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/IndentArray:
  EnforcedStyle: consistent

Style/IndentHash:
  EnforcedStyle: consistent

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/OptionHash:
  Enabled: true

Style/SafeNavigation:
  ConvertTry: true

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
